{
 "title": "HP iLO",
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server",
    "query": {
     "query": "label_values(hpilo_bios_hardware, server_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_firmware_version{server_name=\"$server_name\"}",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Power consumtion",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(hpilo_power_supplies_readings{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}[$__range]) / (count_over_time(hpilo_power_supplies_readings{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}[1m]) * 60) / 1000",
     "legendFormat": "Power"
    },
    {
     "expr": "sum_over_time(hpilo_power_supplies_readings{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}[$__range]) / (count_over_time(hpilo_power_supplies_readings{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}[1m]) * 60) / 1000 * 2000",
     "legendFormat": "Estimated money"
    }
   ]
  },
  {
   "title": "Power reading",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpilo_power_supplies_readings{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}) by (server_name)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Power reading",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(hpilo_power_supplies_readings{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}) by (server_name)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Server hardware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_firmware_version{server_name=\"$server_name\"}",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "iLO version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_firmware_version{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Components Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(hpilo_temperature_value{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}) by (server_name, sensor)",
     "legendFormat": "{{server_name}} {{label}}"
    }
   ]
  },
  {
   "title": "Overall health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_storage_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hpilo_fans_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hpilo_bios_hardware_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hpilo_memory_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hpilo_power_supplies_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hpilo_processor_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hpilo_network_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hpilo_temperature_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hpilo_vrm_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpilo_memory_detail{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"})",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Memory speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, hpilo_memory_detail{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"})",
     "legendFormat": "{{operating_frequency}}"
    }
   ]
  },
  {
   "title": "PSU status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpilo_power_supplies_detail{capacity_w!=\"0\", server_name=\"$server_name\", product_name!=\"Unknown HP Server\"}) by (psu_id, capacity_w)",
     "legendFormat": "PSU {{psu_id}} - {{capacity_w}} W"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hpilo_fan_speed{server_name=\"$server_name\"}) by (fan)",
     "legendFormat": "Fan {{fan_id}}"
    }
   ]
  },
  {
   "title": "CPU name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, hpilo_processor_detail{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU socket",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hpilo_processor_detail{server_name=\"$server_name\", product_name!=\"Unknown HP Server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSU status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpilo_power_supply_status{server_name=\"$server_name\", product_name!=\"Unknown HP Server\",label!~\"Battery.*\"}",
     "legendFormat": "{{ps}}"
    }
   ]
  }
 ]
}